---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    security_opt:
      - seccomp:unconfined
    privileged: true
    pre_build_image: true
    published_ports:
      - "80:80"
    environment:
      container: docker

provisioner:
  name: ansible

verifier:
  name: ansible