- name: Install tinyproxy
  apt:  name=tinyproxy state=present
  become: true

- name: Restart tinyproxy
  service: name=tinyproxy state=restarted
  become: true
  tags: tinyproxy

- name: Tiny proxy config file
  template: src=tinyproxy.j2 dest=/etc/tinyproxy/tinyproxy.conf
  become: true

- name: Install Apache
  apt:  name=apache2 state=present
  become: true

- name : Start Apache
  service: name=apache2 state=started
  become: true
  tags: apache
